# Generated by Django 3.1.4 on 2020-12-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=122)),
                ('lastname', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=90)),
                ('subject', models.TextField()),
            ],
        ),
    ]
